# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Switzerland
    url: switzerland/
    weight: 20
  - name: Italy
    url: italy/
    weight: 30
  - name: Topics
    url: tags/
    weight: 80
  - name: Uses
    url: uses/
    weight: 90
